### ISSUE TITLE
Printing trace buffer because: Looks like your uhk60 crashed.

### ISSUE THREAD

**Issue by jaeryongim** [UltimateHackingKeyboard/firmware#1287]
Today, after work, I ran uhk agent again and got this error. 
The keyboard is working fine, but the letters OUT appear and disappear in the upper left display.
I did a firmware update again just in case, but the error is still there.

keyboard: uhk60
modules: trackball, key cluster
firmware version : 14.0.1
```
Printing trace buffer because: Looks like your uhk60 crashed.
Last EV: 0
Trace:
()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()
()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()
()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()()
()()()()()()()()()()()()()()()()()()()()()()()Rebooting...######

Printing trace buffer because: Looks like your uhk60 crashed.
Last EV: 0
Trace:
3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l
3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l
3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l
3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)Rebooting...######

Printing trace buffer because: Looks like your uhk60 crashed.
Last EV: 0
Trace:
3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l
3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l
3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l
3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)(l3)Rebooting...######
```

**Comment by jaeryongim** [comment]
It's weird. Apparently the error message was alive when I reconnected the USB a little while ago, but when I reconnected the USB after creating the issue, it disappeared.
What was this error?

**Comment by kareltucek** [comment]
We know about this getting triggered when flashing module firmware. That should be fixed by https://github.com/UltimateHackingKeyboard/firmware/pull/1286 

As a rule of thumb, if the trace ends in `Rebooting...###` then it was a controlled and intended reboot, which for some reason triggered the crash report logic. You can ignore these. 

Powercycling should make it go away.

**Comment by jaeryongim** [comment]
@kareltucek thx !!!

**Comment by jaeryongim** [comment]
@kareltucek @mondalaci  
When I turned the computer back on after work today, I got the same error on the left display, and again, reconnecting the USB made it go away.
 Reconnecting the USB every time doesn't seem like a good idea.
Can you do a little more research on this?

<img width="1125" alt="Image" src="https://github.com/user-attachments/assets/84c0d5c7-041e-4da6-aafe-e1cc04a2754f" /> 

below uhk agent messages

`
Printing trace buffer because: Looks like your uhk60 crashed.
Last EV: 0
Trace:
w <   x RdA  ss   z He"} @ D      @  3e 1 * D  Mr   Y      `aE- 
Y sI)G  Q  " #:    9 %%     z  Jg E   ]  ! Tl  ]`b[dr ~ o   E [p
    _  z 2 oP\pv\^  G 7m  R y)   e   Q    t    Q &0 $ =Mqo   >x 
U x  1{ e  <   .}| A   @         e     }nWO: E ul 16 w9i8 ######
`

**Comment by kareltucek** [comment]
@jaeryongim that is clearly a different cause. Unfortunatelly, except the last `######`, the content is just random bytes. 

Please upgrade to latest firmware, which is 14.2.0, from https://github.com/UltimateHackingKeyboard/firmware/releases, and let us know if it reappears.

Edit: actually, I will throw in more logging and post a new firmware. This looks like it crashed on boot before it had time to record any traces 🤨

**Comment by jaeryongim** [comment]
@kareltucek 

i updated 14.2.0 (download "uhk-firmware-14.2.0.tar.gz" and then choose firmware file option on uhk agent)
the reason I left the update instructions above is that I've never updated the agent to “.tar” before, so I just wanted to make sure I didn't do it wrong.

After updating, I got the message below and an “ERR” error on the display, but again, the “ERR” disappeared after reconnecting the usb.
I'll see if the above happens again tonight or tomorrow when I turn the computer off and on again after a long period of inactivity.

`
Printing trace buffer because: Looks like your uhk60 crashed.
EV: 0
Tag: v14.2.0
Trace:
1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i
1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i
1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i
1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1]Rebooting...######
`

**Comment by pcooke9** [comment]
> I just wanted to make sure I didn't do it wrong.

Yes, that's the correct way to flash a firmware version that's not bundled with Agent.🙂

**Comment by jaeryongim** [comment]
@kareltucek  
When I turned the computer back on today, I got the message below and the display still showed the “ERR” error message.

`
QWERTY for Mac
 keymap (
QWM
) 
Layers:
Printing trace buffer because: Looks like your uhk60 crashed.
EV: 0
Tag: v14.2.0
Trace:
][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1
][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1
][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1
][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1][i1]###
`

**Comment by kareltucek** [comment]
@jaeryongim please flash this firmware and lets see if it provides more details: 

[uhk-firmware-14.2.0-reasons_v1.2.tar.gz](https://github.com/user-attachments/files/20976791/uhk-firmware-14.2.0-reasons_v1.2.tar.gz)

**Comment by jaeryongim** [comment]
@kareltucek 

i tried the new "uhk-firmware-14.2.0-reasons_v1.2.tar.gz" update and this time no message came out in the agent after the update. (No ERR message on the display either)

i'll check tomorrow after work to see if I get the same error message as before and leave a message.

Thank you for your help.!!

**Comment by kareltucek** [comment]
Thank you for *your*! 😊

**Comment by jaeryongim** [comment]
@kareltucek 
As expected, I turned on my computer today and got an error.
Below is the log output from the agent. 


`
QWERTY for Mac
 keymap (
QWM
) 
Layers:
Printing trace buffer because: Looks like your uhk60 crashed.
EV: 0
Tag: reasons_v1.2
=== K22P121M120SF7 Reset Cause Debug ===
RCM_SRS0:  0x82
RCM_SRS1:  0x00
RCM_SSRS0: 0x82
RCM_SSRS1: 0x00
PMC_LVDSC1: 0x10
PMC_LVDSC2: 0x80
PMC_REGSC:  0x04
SCB_HFSR:  0x00000000
SCB_CFSR:  0x00000000
SCB_BFAR:  0xE000ED38
SCB_MMFAR: 0xE000ED34

=== Reset Cause Analysis ===
Power-On Reset detected
Loss of Clock Reset detected
Low-Voltage Warning Flag set
Trace:
][i1][i1][i4][i1][i4][i1][i1][i4][i1][i1][i4][i1][i1][i4][i1][i1
][i4][i1][i4][i1][i4][i1][i1][i1][i1][i4][i1][i4][i1][i4][i1][i1
][i4][i1][i1][i1][i4][i1][i4][i1][i1][i4][i1][i1][i4][i1][i1[i4]
][i1][i1][i4][i1][i4][i1][i1][i4][i1][i4][i1][i1][i1][i4][i1]###
`

**Comment by kareltucek** [comment]
Are you fully shutting the computer, or is it in some kind of sleep mode?

**Comment by kareltucek** [comment]
Anyways, firmware from https://github.com/UltimateHackingKeyboard/firmware/actions/runs/16021486678 should fix it.

**Comment by jaeryongim** [comment]
@kareltucek the above issues always occur when I completely shut down computer and then turn it back on after a long period of time.

**Comment by jaeryongim** [comment]
@kareltucek i'll comment again after the update when the version you say is fixed is released. thx !!

**Comment by jaeryongim** [comment]
@kareltucek hi 
I got the firmware of the current master branch last night and updated it, but I'm still getting “ERR” on the display, and the error below is coming from the agent.
Could you check it one more time? 🥹🥹

` 
QWERTY for Mac
 keymap (
QWM
) 
Layers:
Printing trace buffer because: Looks like your uhk60 crashed.
EV: 0
Tag: v14.2.1
=== K22P121M120SF7 Reset Cause Debug ===
RCM_SRS0:  0x82
RCM_SRS1:  0x00
RCM_SSRS0: 0x82
RCM_SSRS1: 0x00
PMC_LVDSC1: 0x10
PMC_LVDSC2: 0x80
PMC_REGSC:  0x04
SCB_HFSR:  0x00000000
SCB_CFSR:  0x00000000
SCB_BFAR:  0xE000ED38
SCB_MMFAR: 0xE000ED34

=== Reset Cause Analysis ===
Power-On Reset detected
Loss of Clock Reset detected
Low-Voltage Warning Flag set
Trace:
][i1][i1][i4][i1][i4][i1][i1][i1][i4][i1][i1[i4]][i1][i4][i1][i1
][i4][i1][i1][i4][i1][i1][i4][i1][i1][i4][i1][i4][i1][i4][i1][i1
][i1][i1][i4][i1][i4][i1][i4][i1][i1][i4][i1][i1][i1][i4][i1][i4
][i1][i1][i4][i1][i4][i1][i1][i1[i4]][i1][i1][i4][i1][i4][i1]###
`

**Comment by kareltucek** [comment]
v14.2.1 was released before that branch was merged. 

Please flash the firmware from the ci action: https://github.com/UltimateHackingKeyboard/firmware/actions/runs/16021486678

**Comment by jaeryongim** [comment]
@kareltucek okay i'll update it right now and check it out when wake up tomorrow. thx !🙏🏻
