### ISSUE TITLE
Transparent keys / keymap

### ISSUE THREAD

**Issue by cwrau** [UltimateHackingKeyboard/firmware#1356]
It would be nice to have the option to make keys or maybe even whole keymaps transparent.

That means that when pressing that key / an unmapped key on that keymap it would just fallthrough to the base/last layer / the last keymap.

That would make it easier to have simple overlays, for example I essentially only have a single keymap, but in reality I have 6; 1 is the one I really use and the other 5 are the same with a couple of keys changed for games that don't allow changing keybinds.

Now, if I want to change a "universal" key I have to do it on all keymaps and even on multiple layers if needed.

**Comment by mhantsch** [comment]
You can use macros and `overlayLayer` to overload keys on a keymap from a layer from this or another keymap. Only keys that are defined on the other layer will be overloaded, the other keys remain as defined in the original layer. To switch back to the original layer, you can `replaceLayer`, which loads all keys, including resetting undefined keys to pure nothingness.

It's not truly a stack of layers with transparent keys, but for your use case this might work. I've used it for similar things.

**Comment by kareltucek** [comment]
Sounds as a reasonable request to me. I wonder why we haven't implemented such thing yet, as well as why such obvious thing wasn't requested before. 

I can imagine two implementations: 

- a new action type, that would be exposed in the key popover
- a macro command that would allow configuring a layer to be transparent

**Comment by mhantsch** [comment]
@kareltucek How would you create the stack of layers? Just in order of layer activation? When would layers get popped off the stack?

e.g. I press and hold `mod`, then `fn`, then `fn2`, then release `fn`. 

After pressing and holding all keys, would the firmware then stack the layers as:

base -> mod -> fn -> fn2

and after I release `fn` would it be:

base -> mod -> fn2

??

How would macro commands play into this, e.g. `holdLayer`, `toggleLayer` and `unToggleLayer`?

**Comment by kareltucek** [comment]
@mhantsch we have a layer stack. Layers are popped off when their switcher is deactivated. (Layers that are not on top of the stack remain there until they are, but are immediately marked as inactive, so we can fall through them correctly).

> After pressing and holding all keys, would the firmware then stack the layers as:
> 
> base -> mod -> fn -> fn2
> 
> and after I release fn would it be:
> 
> base -> mod -> fn2

Yes.

> How would macro commands play into this, e.g. holdLayer, toggleLayer and unToggleLayer?

Both layer switching systems should be fully integrated these days. 

I.e., typical order of operations to untoggle, if both toggle and untoggle are mapped in the mod layer is 

- base 
- _press `holdLayer mod`_
- base -> (held) mod 
- _tap `toggleLayer mod`_
- base -> (held) mod held -> (toggled) mod 
- _release `holdLayer mod`_
- base -> (inactive, held) mod  -> (toggled) mod
- ...
- _press `holdLayer mod`_
- base -> (inactive, held) mod  -> (toggled) mod -> (held) mod
- _tap `untoggleLayer`_
- base -> (inactive, held) mod -> (inactive, toggled) mod  -> (held) mod
- _release `holdLayer mod`_
- base

**Comment by mhantsch** [comment]
Cool, I just remembered that there were originally two systems, and I wasn't sure how that would play out. Sounds good though, the way you've just described it!

**Comment by mondalaci** [comment]
To my knowledge, separate empty and transparent key actions are implemented by QMK/ZMK. The fact that we only have an empty action after all these years means that the transparent action would be used very rarely, so it's worth considering whether it'd help.

I think it's more sensible to create separate keymaps for each game, containing only the keys that need to be overridden. When having one master keymap (abbreviation MAS) and six GAx game keymaps (GA1 to GA6), the `$onKeymapChange GA1` to `$onKeymapChange GA6` macros would contain:

```
replaceLayer base MAS base
replaceLayer mod MAS mod
// replace other layers if needed
overlayKeymap GAx
```

As a casual gamer, I've just adopted this setup. It works great, it's very clean, and the empty key actions compress well.

I dislike the layer-based solution. To me, the keymap-based solution is cleaner as the current keymap is explicitly shown on the display, and it's easy to create multiple layers per keymap.

@kareltucek How about also having a `replaceKeymap` command to simplify such use cases, and possibly a convenience `$currentKeymap` constant as well?

**Comment by kareltucek** [comment]
That's a cool hack actually. In this light, it makes sense.

**Comment by kareltucek** [comment]
Based on Laszlos feedback, this new api is to be added: 

```
replaceKeymap
KEYMAPID = current
LAYERID = current
```

I am not convinced it substitutes the requested functionality though ;-).

**Comment by mondalaci** [comment]
> I am not convinced it substitutes the requested functionality though ;-).

It doesn't, but grasping transparent vs empty actions would generate mental overhead for users, and I think the keymap-based solution is better.

**Comment by mhantsch** [comment]
@mondalaci:
> separate empty and transparent key actions are implemented by QMK/ZMK

That is correct. You can bind &none or &transparent to a key. The first would ignore that keypress and not generate any event, the second would trace down the layer stack until it finds a non-transparent action and perform that.

> grasping transparent vs empty actions would generate mental overhead

I don't agree. It depends on your starting point and previous experience. For users that come from QMK or ZMK, this is very natural. They would look for such a layer concept on the UHK as well.

------

On the other hand, I have used the keymap replace/overload concept for some of my keymaps. This can be quite elegant. It requires a bit more knowledge of macros and "programming skills" (mindset of a SW developer). For example, my "numpad" keymap keeps all layers from my regular keymap:

**$onKeymapChange NMX**:
```
replaceLayer mod CMX mod
replaceLayer mouse CMX mouse
replaceLayer fn CMX fn
replaceLayer fn2 CMX fn2
replaceLayer fn3 CMX fn3
replaceLayer fn4 CMX fn4
replaceLayer fn5 CMX fn5
set keymapAction.fn.isoKey macro initCMX
set keymapAction.fn.slashAndQuestionMark macro initCMX
set keymapAction.fn3.isoKey macro initCMX
```
(**initCMX** just switches back to my regular primary keymap.)

`replaceKeymap` would shorten this macro quite a bit.

------

My HRM setup uses overlays, so it can be loaded onto pretty much any keymap:

**hrm-on**:
```
setVar hrm_active 1
setVar hrm_avoid_same 50
overlayLayer base HRM mod
setLedTxt 666 'H++'
```

**hrm-off**:
```
setVar hrm_active 0
setVar hrm_avoid_same 50
overlayLayer base HRM base
setLedTxt 666 'H--'
```

The **HRM** keymap contains only mappings for the HRM keys on the *mod* layer, and standard mappings on the *base* layer. (Ideally, I would want to rename the layers to *hrm* and *off*.) All other keys are undefined and thus, remain at their regular mappings with `overlayLayer`.

------

I think both concepts have merits. Why wouldn't we allow both?

1) Layers:
- The layer stack already exists.
- Add a flag to a layer that indicates that "None" means transparent for this layer. (Or is "None" action already handled as transparent when layers are stacked? I can't remember.)
- Alternatively, make "None" always act transparently, and define a new "Do nothing" (`noOp`) action. (I think it would be used seldomly, so it wouldn't be horrible if it didn't compress well.)
- No macros needed.
- Similar concept to QMK/ZMK layers.

2) Keymaps:
- Very flexible, completely customisable with macros.
- Needed macro instructions already exist.
- Needs programming skills and developer mindset.
- Feels natural when starting from UHK / Agent concept.
- Maybe needs better examples and documentation for users to learn how to best apply.

------

@kareltucek: 
> `replaceKeymap`
> `KEYMAPID = current`
> `LAYERID = current`

Why do you need a LAYERID if you want to replace a whole keymap?

Can the concept of `replaceLayer` and `overlayLayer` be extended to either do it for one layer (specified by LAYERID) or a whole keymap (if no layers are specified)?

**Comment by kareltucek** [comment]
> Why do you need a LAYERID if you want to replace a whole keymap?

Only for completeness sake. 

> Can the concept of replaceLayer and overlayLayer be extended to either do it for one layer (specified by LAYERID) or a whole keymap (if no layers are specified)?

No idea what you are asking. We already have overlayKeymap, and I had promised to deliver replaceKeymap.

**Comment by mhantsch** [comment]
> > Why do you need a LAYERID if you want to replace a whole keymap?
> Only for completeness sake.

But what would it do? Replace only that layer? That's identical to replaceLayer, isn't it?

> I had promised to deliver replaceKeymap.

Oh, I see. Makes sense. ✅

**Comment by kareltucek** [comment]
> But what would it do? Replace only that layer? That's identical to replaceLayer, isn't it?

Substitute current layer id wherever a LAYERID parameter is required. It is not meant to be used specifically with replace and overlay layers, although of course you could.

**Comment by mhantsch** [comment]
> Substitute current layer id

Oh I see, so I could write

```
overlayLayer current OVL current
```

with the intention of overlaying the current layer with the same layer from the OVL keymap?

Or 

```
replaceLayer current current fn3
```

with the intention of replacing the current layer with the fn3 layer of the current keymap?

**Comment by mhantsch** [comment]
What may be useful is to be able to specify a list of layers to replace/overlay in a single command, so instead of 

```
replaceLayer mouse CMX mouse
replaceLayer fn CMX fn
replaceLayer fn2 CMX fn2
replaceLayer fn3 CMX fn3
replaceLayer fn4 CMX fn4
replaceLayer fn5 CMX fn5
```

I could write

```
replaceLayerFromKeymap CMX mouse fn fn2 fn3 fn4 fn5
```

to replace all layers except the mod layer.

Maybe a syntax can be found that doesn't need a separate `replaceLayerFromKeymap` command, but can be piggy-backed onto the existing `replaceLayer` and `overlayLayer` commands? Maybe with `replaceKeymap`/`overlayKeymap` as a `LAYERID*` list?

```
replaceKeymap CMX mouse fn fn2 fn3 fn4 fn5
```

Without a layer list, it would of course replace all layers.

**Comment by kareltucek** [comment]
Yes.

**Comment by kareltucek** [comment]
You are overthinking. The basic set of overlayLayer, replaceLayer, overlayKeymap and replaceKeymap is just fine.

**Comment by mondalaci** [comment]
Resolved by #1358, reducing the my earlier https://github.com/UltimateHackingKeyboard/firmware/issues/1356#issuecomment-3311656132 example to:

```
replaceKeymap MAS
overlayKeymap current
```

**Comment by kareltucek** [comment]
#1358 has little to do with this feature request...

**Comment by mondalaci** [comment]
How so? It indirectly addresses the mentioned use case.

**Comment by kareltucek** [comment]
The PR is a bit of syntactic sugar over already existing functionality. It didn't really add any new functionality.

I was not saying anything about whether or not it is adequate to close the feature request, just that the reasoning was not valid.

----

 As for actual usecases that are totally not solved and may be solved by some variation of the above, for instance nested transparent layers. You can't do that with current feature set.

(Again I am not saying anything about whether or not we want or need them. I just think that we should not back our decisions by logical fallacies.)

**Comment by mondalaci** [comment]
Gotcha. I think we should not spend more time on this.
