### ISSUE TITLE
Media key scancode repetition

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#72]
On Windows {7,8,10} consumer codes are being repeated (quickly toggled) when relevant keys are pressed. I encountered similar issues earlier and though I fixed them all, but apparently not. I'll look into how Windows sends HID reports, and adjust `UpdateUsbReports()` accordingly.

**Comment by Lauszus** [comment]
I believe this is the cause of #85 and possibly also #84.

**Comment by Lauszus** [comment]
I believe https://github.com/UltimateHackingKeyboard/firmware/pull/104/commits/15d09552a4d475032869594cf3a0f6eb2674a822 fixes this.

**Comment by mondalaci** [comment]
Unfortunately, this issue still stands.

**Comment by eltang** [comment]
I'm no USB expert, but I notice that the USB stack sends reports in response to kUSB_DeviceHidEventSendResponse. I was expecting it to rely on kUSB_DeviceHidEventGetReport, based on what I've seen other USB stacks do. What was the rationale for using the current method?

@Lauszus I believe that the code in the USB stack expects that IsUsbBasicKeyboardReportSent and friends are always false by the time control flow reaches it. It sends reports and sets those variables to true no matter what their previous values were.

**Comment by piratk** [comment]
It seems that this issue also affects launching the calculator, yielding a fair bunch of calculators if used on Windows.

**Comment by mondalaci** [comment]
Yes, we know. Calculator is also a media scancode.

**Comment by Lauszus** [comment]
@eltang this is how all the other interfaces does it as well and they seem to not have this issue?

**Comment by Lauszus** [comment]
I just captured the packets while the USB keyboard was just plugged in. I then held down the volume up button and then let go a couple of seconds later.

The scan codes are NOT toggled. Everything looks alright.

Are you sure that this is not the expected behaviour on Windows? I know that in older version of Windows you could hold SUPER+e down and you could crash Windows as it would just keep opening a file explorer window. However this is fixed in Windows 10.

Here is the Wireshark capture: [volume_up.pcapng.zip](https://github.com/UltimateHackingKeyboard/firmware/files/2077997/volume_up.pcapng.zip)

**Comment by Lauszus** [comment]
Here is the output after applying a filer and only outputting the data: 
[data.txt](https://github.com/UltimateHackingKeyboard/firmware/files/2078085/data.txt)

FYI I exported the data using the following command:

```bash
tshark -r volume_up.pcapng -Y usb.darwin.endpoint_address==0x84 -T fields -e usb.capdata > data.txt
```

Note that you should replace ```usb.darwin.endpoint_address``` with ```usb.bEndpointAddress``` if you are running anything except for Mac.

**Comment by Jos512** [comment]
PS: This issue is linked from the UltimateHackingKeyboard start guide, saying:

> Windows users, the Media key scancode repetition firmware bug makes media keys repeat very quickly on Windows. We're working on fixing this bug, so please bear with us.

If I understand the above merges correctly, the bug is fixed. So that information can be removed from the start guide. :slightly_smiling_face:

**Comment by mondalaci** [comment]
This is still an issue because we flash 8.2.5 in the factory due to the freeze bug. Will remove this sentence from the onboarding guide when the time comes.

**Comment by jlsjonas** [comment]
Why is this issue closed? the merge that fixes it got reverted and the issue still persists for windows users. https://github.com/UltimateHackingKeyboard/firmware/pull/129

Not just for volume, but also for play/pause etc.
